name: devops-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
      - name: executa comando
        run: echo "Configuração inicial do pipeline" 

deploy-dev:
  runs-on: ubuntu-latest
  enviroment:
    name: dev
    url: 'https://www.pucminas.br/destaques/Paginas/default.aspx'
  needs: build 
  steps:
    - name: Run a one-line script
      run: echo Deploy Dev
  
  deploy-prod:
   runs-on: ubuntu-latest
   enviroment: prod
   url: 'https://www.pucminas.br/destaques/Paginas/default.aspx'
   needs: deploy-dev
   steps:
    - name: Run a one-line script
      run: echo Deploy Prod
      
      steps:            
      - name: run a one-line script
        run: echo "Configuração inicial do pipeline" 
